## Numpy Array Operations

In [1]:
import numpy as np

### Indexing & Slicing

In [ ]:
#1D
arr = np.arange(11)
print("arr: ", arr)
print("basic slicing: ", arr[2:7])
print("step slicing: ", arr[1:8:2])
print("negative slicing: ", arr[-3:])

arr:  [ 0  1  2  3  4  5  6  7  8  9 10]
basic slicing:  [2 3 4 5 6]
step slicing:  [1 3 5 7]
negative slicing:  [ 8  9 10]


In [8]:
#2D
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8 ,9]])
print("specific element: ", arr_2d[1, 2])
print("entire row: ", arr_2d[1])
print("entire col: ", arr_2d[:, 2])


specific element:  6
entire row:  [4 5 6]
entire col:  [3 6 9]


#### Reverse an Array using Indexing

In [19]:
test_arr = np.array([5, 6, 7, 8, 9])
reversed = test_arr[::-1]
print(reversed)

[9 8 7 6 5]


### Sorting

In [ ]:
#1D
unsorted = np.array([3, 4, 7, 9, 1, 5, 3, 7, 2])
print("sorted arr: ", np.sort(unsorted))

sorted arr:  [1 2 3 3 4 5 7 7 9]


In [ ]:
#2D
unsorted_2d = np.array([[7, 4], [2, 0], [1, 6]])
print("org matrix: \n", unsorted_2d)
print("sorted matrix by col: \n", np.sort(unsorted_2d, axis=0)) 
print("sorted matrix by row: \n", np.sort(unsorted_2d, axis=1)) 
#axis -> 0 (col wise) & 1 (row wise) sorting

org matrix: 
 [[7 4]
 [2 0]
 [1 6]]
sorted matrix by col: 
 [[1 0]
 [2 4]
 [7 6]]
sorted matrix by row: 
 [[4 7]
 [0 2]
 [1 6]]


### Filter

In [12]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_nums = nums[nums % 2 == 0]
print("Even Numbers: ", even_nums)

Even Numbers:  [ 2  4  6  8 10]


#### Filter with Mask 

In [ ]:
#mask -> expression for evaluation
mask = nums > 5
print(">5: ", nums[mask])

>5:  [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [ ]:
indices = [0, 2, 4]
print(nums[indices])

where_res = np.where(nums > 5) #stores idxs acc to the condition
print("np where: ", nums[where_res])

[1 3 5]
np where:  [ 6  7  8  9 10]


In [22]:
#np.where() -> also creates an array but acc to conditions
condition_arr = np.where(nums > 5, nums * 2, nums)
print(condition_arr)

condition_arr = np.where(nums > 5, "true", "false")
print(condition_arr)

[ 1  2  3  4  5 12 14 16 18 20]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [ ]:
#if(nums > 5) {
#   nums * 2
# else {
#   nums
#}


### Adding & Removing Data

In [ ]:
#Merging two Arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)


[1 2 3 4 5 6]


### Array Compatibility


In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 0])
c = np.array([7, 8 ,9])

print("Compatibility Shapes: ", a.shape == b.shape)

Compatibility Shapes:  False


### Adding / Deleting New Rows & Cols

In [ ]:
#ADDING

org = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

#vstack - vertical stack - adds new row
with_new_row = np.vstack((org, new_row))
print(org)
print(with_new_row)

print("\n")

#hstack - horizontal stack - adds new col
new_col = np.array([[8], [9]])
with_new_col = np.hstack((org, new_col))
print(org)
print(with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


[[1 2]
 [3 4]]
[[1 2 8]
 [3 4 9]]


In [ ]:
#DELETING

arr = np.array([1, 2, 3, 4])
deleted = np.delete(arr, 2) #idx
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4]
[1 2 3 4]


### Adding / Multiplication Operations

In [36]:
#Adding

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(np.add(a1, a2))

print("\n")

a3 = np.array([[1, 2, 3], [4, 5, 6]])
a4 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.add(a3, a4))

[5 7 9]


[[ 8 10 12]
 [14 16 18]]


In [39]:
#Multiply

print(np.multiply(a1, 3))
print(np.multiply(a1, a2))

print("\n")

print(np.multiply(a3, 2))
print(np.multiply(a3, a4))

[3 6 9]
[ 4 10 18]


[[ 2  4  6]
 [ 8 10 12]]
[[ 7 16 27]
 [40 55 72]]
