## NumPy Arrays & Basics

In [1]:
import numpy as np

### Creating Array from List

In [2]:
arr_1d = np.array([1, 2, 3])
print("1D Array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array: ", arr_2d)

1D Array:  [1 2 3]
2D Array:  [[1 2 3]
 [4 5 6]]


### List vs NumPy Array

In [3]:
py_list = [1, 2, 3]
print("Py List Multi: ", py_list * 2)

np_array = np.array([1, 2, 3]) #element wise multiplication
print("Py Array Multi: ", np_array * 2)

Py List Multi:  [1, 2, 3, 1, 2, 3]
Py Array Multi:  [2 4 6]


In [5]:
import time 

start = time.time()
py_list = [i*2 for i in range(100000)]
print("py list operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(100000) * 2 #numpy computation time is much faster 
print("np array operation time: ", time.time() - start)

py list operation time:  0.006357908248901367
np array operation time:  0.0007390975952148438


### Creating Array from Scratch

In [10]:
zeros = np.zeros((3, 4)) #to create a zeros array
print("zeros array: \n", zeros)

ones = np.ones((4, 5)) #to create a ones array
print("ones array: \n", ones)

full = np.full((2, 2), 8) #to create a constants array
print("full array: \n", full)

random = np.random.random((2, 5)) #random class -> random() -> to create a random array - values: [0, 1]
print("random array: \n", random)

sequence = np.arange(0, 11, 2) #(start, stop, step) - stop (not included)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full array: 
 [[8 8]
 [8 8]]
random array: 
 [[0.22298209 0.23253612 0.53946271 0.31570155 0.29323613]
 [0.83077692 0.58180986 0.24857819 0.91618938 0.11263635]]
sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix & Tensor

In [11]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], #multi-dimensional arrays
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape: ", arr.shape) #rows & cols
print("Dimensions: ", arr.ndim) #dimensions
print("Size: ", arr.size) #no of elements
print("Data type: ", arr.dtype) #data type of elements 

Shape:  (2, 3)
Dimensions:  2
Size:  6
Data type:  int64


### Array Reshaping

In [ ]:
arr = np.arange(12) #non-exclusive range
print("org arr: ", arr)

reshaped = arr.reshape((3, 4)) #reshaping into rows & cols
print("reshaped arr: \n", reshaped)

flatten = reshaped.flatten() #flatting - single row
print("flatten arr: ", flatten)

#ravel -> (returns view, instead of copy)
raveled = reshaped.ravel()
print("raveld arr: ", raveled)

#transpose - rows -> cols | cols -> rows
transpose = reshaped.T
print("transposed arr: \n", transpose)

org arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped arr: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveld arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed arr: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
